name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'
        
    - name: Check gofmt
      run: '[[ $(gofmt -l ./ | head -c1 | wc -c) -eq 0 ]]'

    - name: Check go vet
      run: go vet ./...
          
    - name: go build
      run: go build -v ./...
      
    - name: go test
      run: go test -v ./...
    